name: qbx-ds-experiments
channels:
- conda-forge
- nodefaults
dependencies:
- blas=*=openblas
- colorama
- compilers
- cython
- git
- gmsh
- immutables
- islpy
- mako
- matplotlib-base
- numpy
- pip
- pocl
- pyopencl
- pyrsistent
- pytest
- python-symengine
- python=3.13
- pytools
- pyvkfft
- recursivenodes
- scipy=1.14.1
- sympy
